name: Build Next.JS Web Application [Spectex.xyz]
on: push
jobs:
    # Build application with pnpm and node js

    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 18.x
              uses: actions/setup-node@v2
              with:
                  node-version: 18.x
            - name: Setup pnpm
              uses: pnpm/action-setup@v2.2.4
              with:
                version: 6.0.2
            - name: Install dependencies
              run: pnpm install
            - name: Build
              run: pnpm run build